# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Chaospixel"

head_title: "Chaospixel | IT Blog"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Blog about Linux, photography and science."

# Tagline near the site title
tagline: "Linux, photography and science."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:


sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://blog.chaospixel.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: "linux"
  url: /categories/linux/
- text: "imaging"
  url: /categories/imaging/
- text: "deepsky"
  url: /categories/deepsky/
- text: Archives
  url: /tags/
- text: Imprint
  url: /imprint.html
#- text: Style Guides
#  url: /style-guide/


# The shortname for your Disqus site to enable comments.
disqus: "blog-chaospixel-com"

# Author information - author info at the bottom of the post
author_name: "Daniel Vogelbacher"
author_bio: "Hi, I'm Daniel, a software developer, Linux administrator and landscape photographer."
author_url:  "https://chaospixel.com"
author_location: "Germany"
author_image: /images/authorimage.png

# Sidebar Add banner
#banner_url: "http://justgoodthemes.com"
#banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_username: "username"
#facebook_username: "username"
#googleplus_username: "+username"
github_username: "cytrinox"
500px_username: "DVogelbacher"
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
#instagram_username: "username"
#pinterest_username: "username"
#linkedin_username: "username"
xing_username: "Daniel_Vogelbacher"
#flickr_username: "cytrinox"

# http://jekyllrb.com/docs/pagination/
#paginate: 5
#paginate_path: '/blog/page:num/'
#gems: [jekyll-paginate]
gems: [jekyll-paginate-v2, jekyll_picture_tag]


picture:
  ignore_missing_images: true
  nomarkdown: false

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 15

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################


permalink: "/:categories/:year/:month/:title.html"
markdown: kramdown
kramdown:
    auto_ids: false

show_drafts: false
highlighter: rouge

#GPGClearsign: true

defaults:
